---
- name: Install et config Apache2
  hosts: all
  become: true

  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: true

    - name: Installer Apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Verifie Apache2 est demarre et active au démarrage
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
