---
- name: Installer vim et vérifier /etc/passwd (Ubuntu)
  hosts: all
  become: true

  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: true

    - name: Installer vim sur Ubuntu
      ansible.builtin.apt:
        name: vim
        state: present

    - name: Vérifier que /etc/passwd existe
      ansible.builtin.stat:
        path: /etc/passwd
      register: passwd_stat
