---
- name: Install et config Apache2
  hosts: all
  become: true

  tasks:
    - name: Mettre à jour la liste des paquets
      ansible.builtin.apt:
        update_cache: true

    - name: Installer Apache2 et MySQl-Server
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mysql-server

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Modifier index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head><title>Apache2</title></head>
          <body>
            <h1>Bonjour depuis Ansible</h1>
          </body>
          </html>
        mode: "0644"
      when: "'apache2' in ansible_facts.packages"

    - name: Verifie Apache2 est demarre et actif au démarrage
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
      when: "'apache2' in ansible_facts.packages"
